import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../redux-setup/Providers";
import { store } from "@/redux-setup/store";
import SideBar from "./../components/SideBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          {/* <section className="flex justify-between"> */}
          {/* <SideBar /> */}
          {children}
          {/* </section> */}
        </body>
      </html>
    </Providers>
  );
}
